# Generated by Django 5.2 on 2026-01-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.CharField(max_length=100, verbose_name='Hora')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('Jóvenes', 'Jóvenes'), ('Iglesia General', 'Iglesia General'), ('Niños', 'Niños'), ('Mujeres', 'Mujeres'), ('Hombres', 'Hombres')], max_length=50, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo/Rol')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Foto')),
                ('whatsapp_link', models.URLField(help_text='Ej: https://wa.me/1234567890', verbose_name='Enlace de WhatsApp')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Tarjeta de Contacto',
                'verbose_name_plural': 'Tarjetas de Contacto',
                'ordering': ['order'],
            },
        ),
    ]
