# Generated by Django 6.0.1 on 2026-01-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('image', models.ImageField(upload_to='event_photos/', verbose_name='Foto del Evento')),
                ('sermon', models.TextField(verbose_name='Sermón Expuesto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Realizado',
                'verbose_name_plural': 'Eventos Realizados',
                'ordering': ['-date'],
            },
        ),
    ]
