# Generated by Django 6.0.1 on 2026-01-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
    ]
