# Generated by Django 5.2 on 2026-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='content_type',
            field=models.CharField(default='image/jpeg', help_text='Ej: image/jpeg', max_length=50, verbose_name='Tipo de archivo'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Datos de la imagen'),
        ),
    ]
