# Generated by Django 5.2 on 2026-01-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_galleryimage_image_galleryimage_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='contactcard',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de archivo'),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Datos de la foto'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de archivo'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Datos de la imagen'),
        ),
    ]
