# Generated by Django 5.2 on 2026-01-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_contactcard_photo_remove_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Jóvenes', 'Jóvenes'), ('Adolescentes', 'Adolescentes'), ('Iglesia General', 'Iglesia General'), ('Niños', 'Niños'), ('Mujeres', 'Mujeres'), ('Hombres', 'Hombres')], max_length=50, verbose_name='Categoría'),
        ),
    ]
